import json
import os

new_keys = {
    "English": {
        "admin_sidebar_dashboard": "Dashboard",
        "admin_sidebar_users": "User Management",
        "admin_sidebar_view_users": "View Users",
        "admin_sidebar_add_user": "Add User",
        "admin_sidebar_search_users": "Search Users",
        "admin_sidebar_parents": "Parent Accounts",
        "admin_sidebar_lessons": "Lesson Management",
        "admin_sidebar_view_lessons": "View Lessons",
        "admin_sidebar_add_lesson": "Add Lesson",
        "admin_sidebar_assessments": "Assessment Management",
        "admin_sidebar_question_bank": "Question Bank",
        "admin_sidebar_create_question": "Create Question",
        "admin_sidebar_ai_recs": "AI Recommendations",
        "admin_sidebar_voice": "Voice Learning",
        "admin_sidebar_languages": "Languages",
        "admin_sidebar_games": "Learning Games",
        "admin_sidebar_reports": "Progress & Reports",
        "admin_sidebar_analytics": "System Analytics",
        "admin_sidebar_export_reports": "Export Reports",
        "admin_sidebar_notifications": "Notifications",
        "admin_sidebar_feedback": "Feedback",
        "admin_sidebar_settings": "Settings",
        "admin_sidebar_logout": "Logout",
        "admin_welcome_title": "Welcome back, Admin! 👋",
        "admin_welcome_subtitle": "Here's what's happening with AI Literacy today.",
        
        "admin_stat_total_users": "Total Users",
        "admin_stat_active_users": "Active Users",
        "admin_stat_total_lessons": "Total Lessons",
        "admin_stat_total_assessments": "Total Assessments",
        "admin_stat_languages_supported": "Languages Supported",
        "admin_stat_completion_rate": "Lesson Completion Rate",
        "admin_stat_voice_assessments": "Total Voice Assessments",
        "admin_stat_todays_regs": "Today's Registrations",
        
        "admin_panel_title_learners": "Student (Learner) Profiles",
        "admin_panel_title_parents": "Parent Portal Accounts",
        "admin_panel_title_content": "Lesson Content Management",
        "admin_panel_title_assessments": "Assessment Question Bank",
        "admin_panel_title_recs": "AI Personalized Recommendations",
        "admin_panel_title_voice": "Voice Learning Attempts Log",
        "admin_panel_title_languages": "Supported Languages & Student Adoption",
        "admin_panel_title_games": "Educational Learning Games Catalog",
        "admin_panel_title_analytics": "System Analytics & Performance Logs",
        "admin_panel_title_reports": "Report Downloads & System Backups",
        "admin_panel_title_notifications": "Send Announcement Notification",
        "admin_panel_title_feedback": "User Feedback & Rating Submissions",
        "admin_panel_title_settings": "System General Settings",
        
        "admin_col_student_name": "Student Name",
        "admin_col_parent_name": "Parent Name",
        "admin_col_parent_email": "Parent Email",
        "admin_col_target_child": "Target Child Account",
        "admin_col_verification": "Verification Status",
        "admin_col_title": "Title",
        "admin_col_category": "Category",
        "admin_col_language": "Language",
        "admin_col_difficulty": "Difficulty",
        "admin_col_media": "Media Assets",
        "admin_col_prompt": "Question Prompt",
        "admin_col_age_group": "Age Group",
        "admin_col_learning_path": "Learning Path",
        "admin_col_coins": "Coins",
        "admin_col_badges": "Badges",
        "admin_col_status": "Status",
        "admin_col_action": "Actions"
    },
    "Telugu": {
        "admin_sidebar_dashboard": "డ్యాష్‌బోర్డ్",
        "admin_sidebar_users": "వినియోగదారుల నిర్వహణ",
        "admin_sidebar_view_users": "వినియోగదారులను చూడండి",
        "admin_sidebar_add_user": "వినియోగదారుని జోడించండి",
        "admin_sidebar_search_users": "వినియోగదారులను శోధించండి",
        "admin_sidebar_parents": "తల్లిదండ్రుల ఖాతాలు",
        "admin_sidebar_lessons": "పాఠాల నిర్వహణ",
        "admin_sidebar_view_lessons": "పాఠాలను చూడండి",
        "admin_sidebar_add_lesson": "పాఠాన్ని జోడించండి",
        "admin_sidebar_assessments": "అంచనా నిర్వహణ",
        "admin_sidebar_question_bank": "ప్రశ్నల నిధి",
        "admin_sidebar_create_question": "ప్రశ్నను సృష్టించండి",
        "admin_sidebar_ai_recs": "AI సిఫార్సులు",
        "admin_sidebar_voice": "వాయిస్ అభ్యాసం",
        "admin_sidebar_languages": "భాషలు",
        "admin_sidebar_games": "అభ్యాస ఆటలు",
        "admin_sidebar_reports": "ప్రగతి & నివేదికలు",
        "admin_sidebar_analytics": "సిస్టమ్ విశ్లేషణ",
        "admin_sidebar_export_reports": "నివేదికల ఎగుమతి",
        "admin_sidebar_notifications": "నోటిఫికేషన్లు",
        "admin_sidebar_feedback": "అభిప్రాయం",
        "admin_sidebar_settings": "సెట్టింగులు",
        "admin_sidebar_logout": "లాగ్ అవుట్",
        "admin_welcome_title": "తిరిగి స్వాగతం, అడ్మిన్! 👋",
        "admin_welcome_subtitle": "ఈరోజు AI అక్షరాస్యతతో ఏమి జరుగుతుందో ఇక్కడ చూడండి.",
        
        "admin_stat_total_users": "మొత్తం వినియోగదారులు",
        "admin_stat_active_users": "క్రియాశీల వినియోగదారులు",
        "admin_stat_total_lessons": "మొత్తం పాఠాలు",
        "admin_stat_total_assessments": "మొత్తం అంచనాలు",
        "admin_stat_languages_supported": "మద్దతు ఉన్న భాషలు",
        "admin_stat_completion_rate": "పాఠం పూర్తి రేటు",
        "admin_stat_voice_assessments": "మొత్తం వాయిస్ అంచనాలు",
        "admin_stat_todays_regs": "నేటి నమోదులు",
        
        "admin_panel_title_learners": "విద్యార్థి (అభ్యాసకుడు) ప్రొఫైల్‌లు",
        "admin_panel_title_parents": "తల్లిదండ్రుల పోర్టల్ ఖాతాలు",
        "admin_panel_title_content": "పాఠ్య విషయాల నిర్వహణ",
        "admin_panel_title_assessments": "అంచనా ప్రశ్నల నిధి",
        "admin_panel_title_recs": "AI వ్యక్తిగతీకరించిన సిఫార్సులు",
        "admin_panel_title_voice": "వాయిస్ అభ్యాస ప్రయత్నాల లాగ్",
        "admin_panel_title_languages": "మద్దతు ఉన్న భాషలు & విద్యార్థుల స్వీకరణ",
        "admin_panel_title_games": "విద్యా అభ్యాస ఆటల కేటలాగ్",
        "admin_panel_title_analytics": "సిస్టమ్ విశ్లేషణ & పనితీరు లాగ్‌లు",
        "admin_panel_title_reports": "నివేదిక డౌన్‌లోడ్‌లు & సిస్టమ్ బ్యాకప్‌లు",
        "admin_panel_title_notifications": "ప్రకటన నోటిఫికేషన్ పంపండి",
        "admin_panel_title_feedback": "వినియోగదారు అభిప్రాయం & రేటింగ్ సమర్పణలు",
        "admin_panel_title_settings": "సిస్టమ్ సాధారణ సెట్టింగులు",
        
        "admin_col_student_name": "విద్యార్థి పేరు",
        "admin_col_parent_name": "తల్లిదండ్రుల పేరు",
        "admin_col_parent_email": "తల్లిదండ్రుల ఇమెయిల్",
        "admin_col_target_child": "లక్ష్య పిల్లల ఖాతా",
        "admin_col_verification": "ధృవీకరణ స్థితి",
        "admin_col_title": "శీర్షిక",
        "admin_col_category": "వర్గం",
        "admin_col_language": "భాష",
        "admin_col_difficulty": "కఠినత",
        "admin_col_media": "మీడియా ఆస్తులు",
        "admin_col_prompt": "ప్రశ్న ప్రాంప్ట్",
        "admin_col_age_group": "వయస్సు సమూహం",
        "admin_col_learning_path": "అభ్యాస మార్గం",
        "admin_col_coins": "నాణేలు",
        "admin_col_badges": "బ్యాడ్జీలు",
        "admin_col_status": "స్థితి",
        "admin_col_action": "చర్యలు"
    },
    "Hindi": {
        "admin_sidebar_dashboard": "डैशबोर्ड",
        "admin_sidebar_users": "उपयोगकर्ता प्रबंधन",
        "admin_sidebar_view_users": "उपयोगकर्ता देखें",
        "admin_sidebar_add_user": "उपयोगकर्ता जोड़ें",
        "admin_sidebar_search_users": "उपयोगकर्ता खोजें",
        "admin_sidebar_parents": "अभिभावक खाते",
        "admin_sidebar_lessons": "पाठ प्रबंधन",
        "admin_sidebar_view_lessons": "पाठ देखें",
        "admin_sidebar_add_lesson": "पाठ जोड़ें",
        "admin_sidebar_assessments": "मूल्यांकन प्रबंधन",
        "admin_sidebar_question_bank": "प्रश्न बैंक",
        "admin_sidebar_create_question": "प्रश्न बनाएं",
        "admin_sidebar_ai_recs": "एआई सिफारिशें",
        "admin_sidebar_voice": "आवाज सीखना",
        "admin_sidebar_languages": "भाषाएं",
        "admin_sidebar_games": "शैक्षणिक खेल",
        "admin_sidebar_reports": "प्रगति और रिपोर्ट",
        "admin_sidebar_analytics": "सिस्टम विश्लेषिकी",
        "admin_sidebar_export_reports": "रिपोर्ट निर्यात करें",
        "admin_sidebar_notifications": "सूचनाएं",
        "admin_sidebar_feedback": "प्रतिक्रिया",
        "admin_sidebar_settings": "सेटिंग्स",
        "admin_sidebar_logout": "लॉग आउट",
        "admin_welcome_title": "वापसी पर स्वागत है, एडमिन! 👋",
        "admin_welcome_subtitle": "आज एआई साक्षरता में क्या हो रहा है, यहां देखें।",
        
        "admin_stat_total_users": "कुल उपयोगकर्ता",
        "admin_stat_active_users": "सक्रिय उपयोगकर्ता",
        "admin_stat_total_lessons": "कुल पाठ",
        "admin_stat_total_assessments": "कुल मूल्यांकन",
        "admin_stat_languages_supported": "समर्थित भाषाएँ",
        "admin_stat_completion_rate": "पाठ पूरा होने की दर",
        "admin_stat_voice_assessments": "कुल आवाज मूल्यांकन",
        "admin_stat_todays_regs": "आज के पंजीकरण",
        
        "admin_panel_title_learners": "छात्र (शिक्षार्थी) प्रोफाइल",
        "admin_panel_title_parents": "अभिभावक पोर्टल खाते",
        "admin_panel_title_content": "पाठ्य सामग्री प्रबंधन",
        "admin_panel_title_assessments": "मूल्यांकन प्रश्न बैंक",
        "admin_panel_title_recs": "एआई व्यक्तिगत सिफारिशें",
        "admin_panel_title_voice": "आवाज सीखने के प्रयासों का लॉग",
        "admin_panel_title_languages": "समर्थित भाषाएँ और छात्र अपनाना",
        "admin_panel_title_games": "शैक्षणिक शिक्षण खेलों की सूची",
        "admin_panel_title_analytics": "सिस्टम विश्लेषिकी और प्रदर्शन लॉग",
        "admin_panel_title_reports": "रिपोर्ट डाउनलोड और सिस्टम बैकअप",
        "admin_panel_title_notifications": "घोषणा अधिसूचना भेजें",
        "admin_panel_title_feedback": "उपयोगकर्ता प्रतिक्रिया और रेटिंग सबमिशन",
        "admin_panel_title_settings": "सिस्टम सामान्य सेटिंग्स",
        
        "admin_col_student_name": "छात्र का नाम",
        "admin_col_parent_name": "अभिभावक का नाम",
        "admin_col_parent_email": "अभिभावक का ईमेल",
        "admin_col_target_child": "लक्षित बाल खाता",
        "admin_col_verification": "सत्यापन स्थिति",
        "admin_col_title": "शीर्षक",
        "admin_col_category": "श्रेणी",
        "admin_col_language": "भाषा",
        "admin_col_difficulty": "कठिनाई",
        "admin_col_media": "मीडिया परिसंपत्तियां",
        "admin_col_prompt": "प्रश्न संकेत",
        "admin_col_age_group": "आयु समूह",
        "admin_col_learning_path": "सीखने का मार्ग",
        "admin_col_coins": "सिक्के",
        "admin_col_badges": "बैज",
        "admin_col_status": "स्थिति",
        "admin_col_action": "कार्रवाई"
    },
    "Tamil": {
        "admin_sidebar_dashboard": "டாஷ்போர்டு",
        "admin_sidebar_users": "பயனர் மேலாண்மை",
        "admin_sidebar_view_users": "பயனர்களைக் காண்க",
        "admin_sidebar_add_user": "பயனரைச் சேர்",
        "admin_sidebar_search_users": "பயனர்களைத் தேடு",
        "admin_sidebar_parents": "பெற்றோர் கணக்குகள்",
        "admin_sidebar_lessons": "பாட மேலாண்மை",
        "admin_sidebar_view_lessons": "பாடங்களைக் காண்க",
        "admin_sidebar_add_lesson": "பாடத்தைச் சேர்",
        "admin_sidebar_assessments": "மதிப்பீட்டு மேலாண்மை",
        "admin_sidebar_question_bank": "கேள்வி வங்கி",
        "admin_sidebar_create_question": "கேள்வியை உருவாக்கு",
        "admin_sidebar_ai_recs": "ஏஐ பரிந்துரைகள்",
        "admin_sidebar_voice": "குரல் கற்றல்",
        "admin_sidebar_languages": "மொழிகள்",
        "admin_sidebar_games": "கற்றல் விளையாட்டுகள்",
        "admin_sidebar_reports": "முன்னேற்றம் & அறிக்கைகள்",
        "admin_sidebar_analytics": "கணினி பகுப்பாய்வு",
        "admin_sidebar_export_reports": "அறிக்கைகளை ஏற்றுமதி செய்",
        "admin_sidebar_notifications": "அறிவிப்புகள்",
        "admin_sidebar_feedback": "கருத்துகள்",
        "admin_sidebar_settings": "அமைப்புகள்",
        "admin_sidebar_logout": "வெளியேறு",
        "admin_welcome_title": "மீண்டும் வருக, நிர்வாகியே! 👋",
        "admin_welcome_subtitle": "இன்று ஏஐ எழுத்தறிவில் என்ன நடக்கிறது என்பதை இங்கே காண்க.",
        
        "admin_stat_total_users": "மொத்த பயனர்கள்",
        "admin_stat_active_users": "செயலில் உள்ள பயனர்கள்",
        "admin_stat_total_lessons": "மொத்த பாடங்கள்",
        "admin_stat_total_assessments": "மொத்த மதிப்பீடுகள்",
        "admin_stat_languages_supported": "ஆதரிக்கப்படும் மொழிகள்",
        "admin_stat_completion_rate": "பாடம் முடித்த விகிதம்",
        "admin_stat_voice_assessments": "மொத்த குரல் மதிப்பீடுகள்",
        "admin_stat_todays_regs": "இன்றைய பதிவுகள்",
        
        "admin_panel_title_learners": "மாணவர் (கற்பவர்) சுயவிவரங்கள்",
        "admin_panel_title_parents": "பெற்றோர் போர்டல் கணக்குகள்",
        "admin_panel_title_content": "பாட உள்ளடக்க மேலாண்மை",
        "admin_panel_title_assessments": "மதிப்பீட்டு கேள்வி வங்கி",
        "admin_panel_title_recs": "ஏஐ தனிப்பயனாக்கப்பட்ட பரிந்துரைகள்",
        "admin_panel_title_voice": "குரல் கற்றல் முயற்சிகளின் பதிவு",
        "admin_panel_title_languages": "ஆதரிக்கப்படும் மொழிகள் & மாணவர் தத்தெடுப்பு",
        "admin_panel_title_games": "கல்வி கற்றல் விளையாட்டுகளின் பட்டியல்",
        "admin_panel_title_analytics": "கணினி பகுப்பாய்வு & செயல்திறன் பதிவுகள்",
        "admin_panel_title_reports": "அறிக்கை பதிவிறக்கங்கள் & கணினி காப்புப்பிரதிகள்",
        "admin_panel_title_notifications": "அறிவிப்பு செய்தியை அனுப்பு",
        "admin_panel_title_feedback": "பயனர் கருத்து & மதிப்பீடு சமர்ப்பிப்புகள்",
        "admin_panel_title_settings": "கணினி பொதுவான அமைப்புகள்",
        
        "admin_col_student_name": "மாணவர் பெயர்",
        "admin_col_parent_name": "பெற்றோர் பெயர்",
        "admin_col_parent_email": "பெற்றோர் மின்னஞ்சல்",
        "admin_col_target_child": "இலக்கு குழந்தை கணக்கு",
        "admin_col_verification": "சரிபார்ப்பு நிலை",
        "admin_col_title": "தலைப்பு",
        "admin_col_category": "வகை",
        "admin_col_language": "மொழி",
        "admin_col_difficulty": "கடினத்தன்மை",
        "admin_col_media": "ஊடக சொத்துக்கள்",
        "admin_col_prompt": "கேள்வி வரியில்",
        "admin_col_age_group": "வயது குழு",
        "admin_col_learning_path": "கற்றல் பாதை",
        "admin_col_coins": "நாணயங்கள்",
        "admin_col_badges": "பேட்ஜ்கள்",
        "admin_col_status": "நிலை",
        "admin_col_action": "செயல்கள்"
    },
    "Kannada": {
        "admin_sidebar_dashboard": "ಡ್ಯಾಶ್‌ಬೋರ್ಡ್",
        "admin_sidebar_users": "ಬಳಕೆದಾರರ ನಿರ್ವಹಣೆ",
        "admin_sidebar_view_users": "ಬಳಕೆದಾರರನ್ನು ವೀಕ್ಷಿಸಿ",
        "admin_sidebar_add_user": "ಬಳಕೆದಾರರನ್ನು ಸೇರಿಸಿ",
        "admin_sidebar_search_users": "ಬಳಕೆದಾರರನ್ನು ಹುಡುಕಿ",
        "admin_sidebar_parents": "ಪೋಷಕರ ಖಾತೆಗಳು",
        "admin_sidebar_lessons": "ಪಾಠ ನಿರ್ವಹಣೆ",
        "admin_sidebar_view_lessons": "ಪಾಠಗಳನ್ನು ವೀಕ್ಷಿಸಿ",
        "admin_sidebar_add_lesson": "ಪಾಠ ಸೇರಿಸಿ",
        "admin_sidebar_assessments": "ಮೌಲ್ಯಮಾಪನ ನಿರ್ವಹಣೆ",
        "admin_sidebar_question_bank": "ಪ್ರಶ್ನೆ ಬ್ಯಾಂಕ್",
        "admin_sidebar_create_question": "ಪ್ರಶ್ನೆ ರಚಿಸಿ",
        "admin_sidebar_ai_recs": "ಎಐ ಶಿಫಾರಸುಗಳು",
        "admin_sidebar_voice": "ಧ್ವನಿ ಕಲಿಕೆ",
        "admin_sidebar_languages": "ಭಾಷೆಗಳು",
        "admin_sidebar_games": "ಕಲಿಕೆಯ ಆಟಗಳು",
        "admin_sidebar_reports": "ಪ್ರಗತಿ ಮತ್ತು ವರದಿಗಳು",
        "admin_sidebar_analytics": "ಸಿಸ್ಟಮ್ ಅನಾಲಿಟಿಕ್ಸ್",
        "admin_sidebar_export_reports": "ವರದಿಗಳನ್ನು ರಫ್ತು ಮಾಡಿ",
        "admin_sidebar_notifications": "ಅಧಿಸೂಚನೆಗಳು",
        "admin_sidebar_feedback": "ಪ್ರತಿಕ್ರಿಯೆ",
        "admin_sidebar_settings": "ಸೆಟ್ಟಿಂಗ್‌ಗಳು",
        "admin_sidebar_logout": "ಲಾಗ್ ಔಟ್",
        "admin_welcome_title": "ಮರಳಿ ಸುಸ್ವಾಗತ, ಅಡ್ಮಿನ್! 👋",
        "admin_welcome_subtitle": "ಇಂದು ಎಐ ಸಾಕ್ಷರತೆಯಲ್ಲಿ ಏನಾಗುತ್ತಿದೆ ಎಂಬುದನ್ನು ಇಲ್ಲಿ ನೋಡಿ.",
        
        "admin_stat_total_users": "ಒಟ್ಟು ಬಳಕೆದಾರರು",
        "admin_stat_active_users": "ಸಕ್ರಿಯ ಬಳಕೆದಾರರು",
        "admin_stat_total_lessons": "ಒಟ್ಟು ಪಾಠಗಳು",
        "admin_stat_total_assessments": "ಒಟ್ಟು ಮೌಲ್ಯಮಾಪನಗಳು",
        "admin_stat_languages_supported": "ಬೆಂಬಲಿತ ಭಾಷೆಗಳು",
        "admin_stat_completion_rate": "ಪಾಠ ಪೂರ್ಣಗೊಳಿಸುವಿಕೆ ದರ",
        "admin_stat_voice_assessments": "ಒಟ್ಟು ಧ್ವನಿ ಮೌಲ್ಯಮಾಪನಗಳು",
        "admin_stat_todays_regs": "ಇಂದಿನ ನೋಂದಣಿಗಳು",
        
        "admin_panel_title_learners": "ವಿದ್ಯಾರ್ಥಿ (ಕಲಿಗ) ಪ್ರೊಫೈಲ್‌ಗಳು",
        "admin_panel_title_parents": "ಪೋಷಕರ ಪೋರ್ಟಲ್ ಖಾತೆಗಳು",
        "admin_panel_title_content": "ಪಾಠ ವಿಷಯ ನಿರ್ವಹಣೆ",
        "admin_panel_title_assessments": "ಮೌಲ್ಯಮಾಪನ ಪ್ರಶ್ನೆ ಬ್ಯಾಂಕ್",
        "admin_panel_title_recs": "ಎಐ ವೈಯಕ್ತೀಕರಿಸಿದ ಶಿಫಾರಸುಗಳು",
        "admin_panel_title_voice": "ಧ್ವನಿ ಕಲಿಕೆ ಪ್ರಯತ್ನಗಳ ಲಾಗ್",
        "admin_panel_title_languages": "ಬೆಂಬಲಿತ ಭಾಷೆಗಳು ಮತ್ತು ವಿದ್ಯಾರ್ಥಿ ಅಳವಡಿಕೆ",
        "admin_panel_title_games": "ಶೈಕ್ಷಣಿಕ ಕಲಿಕೆ ಆಟಗಳ ಕ್ಯಾಟಲಾಗ್",
        "admin_panel_title_analytics": "ಸಿಸ್ಟಮ್ ಅನಾಲಿಟಿಕ್ಸ್ ಮತ್ತು ಕಾರ್ಯಕ್ಷಮತೆ ಲಾಗ್‌ಗಳು",
        "admin_panel_title_reports": "ವರದಿ ಡೌನ್‌ಲೋಡ್‌ಗಳು ಮತ್ತು ಸಿಸ್ಟಮ್ ಬ್ಯಾಕಪ್‌ಗಳು",
        "admin_panel_title_notifications": "ಪ್ರಕಟಣೆ ಅಧಿಸೂಚನೆ ಕಳುಹಿಸಿ",
        "admin_panel_title_feedback": "ಬಳಕೆದಾರರ ಪ್ರತಿಕ್ರಿಯೆ ಮತ್ತು ರೇಟಿಂಗ್ ಸಲ್ಲಿಕೆಗಳು",
        "admin_panel_title_settings": "ಸಿಸ್ಟಮ್ ಸಾಮಾನ್ಯ ಸೆಟ್ಟಿಂಗ್‌ಗಳು",
        
        "admin_col_student_name": "ವಿದ್ಯಾರ್ಥಿ ಹೆಸರು",
        "admin_col_parent_name": "ಪೋಷಕರ ಹೆಸರು",
        "admin_col_parent_email": "ಪೋಷಕರ ಇಮೇಲ್",
        "admin_col_target_child": "ಗುರಿ ಮಗುವಿನ ಖಾತೆ",
        "admin_col_verification": "ಪರಿಶೀಲನೆ ಸ್ಥಿತಿ",
        "admin_col_title": "ಶೀರ್ಷಿಕೆ",
        "admin_col_category": "ವರ್ಗ",
        "admin_col_language": "ಭಾಷೆ",
        "admin_col_difficulty": "ಕಠಿಣತೆ",
        "admin_col_media": "ಮಾಧ್ಯಮ ಆಸ್ತಿಗಳು",
        "admin_col_prompt": "ಪ್ರಶ್ನೆ ಪ್ರಾಂಪ್ಟ್",
        "admin_col_age_group": "ವಯಸ್ಸಿನ ಗುಂಪು",
        "admin_col_learning_path": "ಕಲಿಕೆಯ ಹಾದಿ",
        "admin_col_coins": "ನಾಣ್ಯಗಳು",
        "admin_col_badges": "ಬ್ಯಾಡ್ಜ್‌ಗಳು",
        "admin_col_status": "ಸ್ಥಿತಿ",
        "admin_col_action": "ಚರ್ಯೆಗಳು"
    },
    "Marathi": {
        "admin_sidebar_dashboard": "डॅशबोर्ड",
        "admin_sidebar_users": "वापरकर्ता व्यवस्थापन",
        "admin_sidebar_view_users": "वापरकर्ते पहा",
        "admin_sidebar_add_user": "वापरकर्ता जोडा",
        "admin_sidebar_search_users": "वापरकर्ते शोधा",
        "admin_sidebar_parents": "पालक खाती",
        "admin_sidebar_lessons": "पाठ व्यवस्थापन",
        "admin_sidebar_view_lessons": "पाठ पहा",
        "admin_sidebar_add_lesson": "पाठ जोडा",
        "admin_sidebar_assessments": "मूल्यांकन व्यवस्थापन",
        "admin_sidebar_question_bank": "प्रश्न बँक",
        "admin_sidebar_create_question": "प्रश्न तयार करा",
        "admin_sidebar_ai_recs": "एआय शिफारसी",
        "admin_sidebar_voice": "आवाज शिकणे",
        "admin_sidebar_languages": "भाषा",
        "admin_sidebar_games": "शैक्षणिक खेळ",
        "admin_sidebar_reports": "प्रगती आणि अहवाल",
        "admin_sidebar_analytics": "सिस्टम विश्लेषिकी",
        "admin_sidebar_export_reports": "अहवाल निर्यात करा",
        "admin_sidebar_notifications": "सूचना",
        "admin_sidebar_feedback": "प्रतिक्रिया",
        "admin_sidebar_settings": "सेटिंग्ज",
        "admin_sidebar_logout": "लॉग आउट",
        "admin_welcome_title": "परत स्वागत आहे, एडमिन! 👋",
        "admin_welcome_subtitle": "आज एआय साक्षरतेमध्ये काय घडत आहे, येथे पहा।",
        
        "admin_stat_total_users": "एकूण वापरकर्ते",
        "admin_stat_active_users": "सक्रिय वापरकर्ते",
        "admin_stat_total_lessons": "एकूण पाठ",
        "admin_stat_total_assessments": "एकूण मूल्यांकन",
        "admin_stat_languages_supported": "समर्थित भाषा",
        "admin_stat_completion_rate": "पाठ पूर्ण होण्याचा दर",
        "admin_stat_voice_assessments": "एकूण आवाज मूल्यांकन",
        "admin_stat_todays_regs": "आजची नोंदणी",
        
        "admin_panel_title_learners": "विद्यार्थी (शिकणारे) प्रोफाइल",
        "admin_panel_title_parents": "पालक पोर्टल खाती",
        "admin_panel_title_content": "पाठ्य सामग्री व्यवस्थापन",
        "admin_panel_title_assessments": "मूल्यांकन प्रश्न बँक",
        "admin_panel_title_recs": "एआय वैयक्तिकृत शिफारसी",
        "admin_panel_title_voice": "आवाज शिकण्याच्या प्रयत्नांचा लॉग",
        "admin_panel_title_languages": "समर्थित भाषा आणि विद्यार्थी दत्तक",
        "admin_panel_title_games": "शैक्षणिक शिक्षण खेळांची सूची",
        "admin_panel_title_analytics": "सिस्टम विश्लेषिकी आणि कार्यप्रदर्शन लॉग",
        "admin_panel_title_reports": "अहवाल डाउनलोड आणि सिस्टम बॅकअप",
        "admin_panel_title_notifications": "घोषणा अधिसूचना पाठवा",
        "admin_panel_title_feedback": "वापरकर्ता प्रतिक्रिया आणि रेटिंग सबमिशन",
        "admin_panel_title_settings": "सिस्टम सामान्य सेटिंग्ज",
        
        "admin_col_student_name": "विद्यार्थ्याचे नाव",
        "admin_col_parent_name": "पालकाचे नाव",
        "admin_col_parent_email": "पालकाचा ईमेल",
        "admin_col_target_child": "लक्ष्यित बाल खाते",
        "admin_col_verification": "सत्यापन स्थिती",
        "admin_col_title": "शीर्षक",
        "admin_col_category": "श्रेणी",
        "admin_col_language": "भाषा",
        "admin_col_difficulty": "काठिण्य",
        "admin_col_media": "मीडिया मालमत्ता",
        "admin_col_prompt": "प्रश्न प्रॉम्प्ट",
        "admin_col_age_group": "वयोगट",
        "admin_col_learning_path": "शिकण्याचा मार्ग",
        "admin_col_coins": "नाणी",
        "admin_col_badges": "बॅज",
        "admin_col_status": "स्थिती",
        "admin_col_action": "कृती"
    }
}

locales = {
    "English": "en.json",
    "Telugu": "te.json",
    "Hindi": "hi.json",
    "Tamil": "ta.json",
    "Kannada": "kn.json",
    "Marathi": "mr.json"
}

base_dir = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
locales_dir = os.path.join(base_dir, "static", "locales")

for lang, filename in locales.items():
    filepath = os.path.join(locales_dir, filename)
    if os.path.exists(filepath):
        print(f"Updating {filename} for {lang}...")
        with open(filepath, "r", encoding="utf-8") as f:
            data = json.load(f)
        
        # Add new keys
        data.update(new_keys[lang])
        
        with open(filepath, "w", encoding="utf-8") as f:
            json.dump(data, f, ensure_ascii=False, indent=4)

print("Done!")
